level: "debug"
development: false
disableCaller: true
disableStacktrace: true
encoding: "console"
encoderConfig:
  messageKey: "Msg"
  levelKey: "Level"
  timeKey: "Time"
  nameKey: "Name"
  callerKey: "Caller"
  stacktraceKey: "St"
  levelEncoder: "capital"
  timeEncoder: "iso8601"
  durationEncoder: "string"
  callerEncoder: "short"
outputPaths:
  - "stdout"
  - "example/multi_level/yaml_out.log"
errorOutputPaths:
  - "stderr"
levelPaths:
  "error":
    - "stderr"
    - "example/multi_level/yaml_err.log"
  "dpanic":
      - "stderr"
      - "example/multi_level/yaml_dpanic.log"
